In [11]:
import numpy as np

In [12]:
a=np.array([[34,5,45,66],[45,25,66,34]])
print(a)

[[34  5 45 66]
 [45 25 66 34]]


In [13]:
# getting element
a[1][2]

66

In [20]:
# getting row
a[0,:]

array([34,  5, 45, 66])

In [21]:
# getting collumn
a[:,3]

array([66, 34])

In [22]:
a[1,3]=24
print(a)
a[:,2]=4
print(a)

[[34  5 45 66]
 [45 25 66 24]]
[[34  5  4 66]
 [45 25  4 24]]
