COPYING A MATRIX

In [1]:
import numpy as np

In [2]:
# PROBLEM IN COPYING A MATRICS
a= np.array([3,4,2])
b=a
b[0]=100
print (a)

[100   4   2]


In [4]:
 # SOLUTION
a= np.array([3,4,2])
b=a.copy()
b[0]=100
print(a)
print(b)

[3 4 2]
[100   4   2]
