In [2]:
print("hyy")

hyy


In [3]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
import numpy as np

In [3]:
a=np.array([34,54,65,36])
print(a)

[34 54 65 36]


In [42]:
b=np.array([[3.0,34.0,5.0],[34.0,45.0,3.0]])
print(b)

[[ 3. 34.  5.]
 [34. 45.  3.]]


In [8]:
print(a*b)

[ 102 1836  325 1224]


In [43]:
b.ndim #dimention

2

In [36]:
b.shape

(2, 3)

In [38]:
b.dtype

dtype('float64')

In [44]:
b.size

6

In [45]:
b.itemsize

8

In [47]:
b.nbytes

48