In [8]:
import numpy as np
from matplotlib import pyplot as plt

## Transpose

In [11]:
a=np.array([[3,4,2],[5,1,0],[9,9,8]])
print(a)

[[3 4 2]
 [5 1 0]
 [9 9 8]]


In [12]:
print(a.T)

[[3 5 9]
 [4 1 9]
 [2 0 8]]


## DETERMINENT

In [20]:
print(np.linalg.det(a))
print(3*(8)-5*(32-18)+9*(-2))

-63.99999999999998
-64


## INVERSE

In [24]:
inv= np.linalg.inv(a)
print(inv)

[[-0.125     0.21875   0.03125 ]
 [ 0.625    -0.09375  -0.15625 ]
 [-0.5625   -0.140625  0.265625]]


## SOLVING EQUATION

##### 3x + 4y+ z=3
##### 9x + y=1
##### y + 9z=0

In [25]:
v= np.array([[3,4,1],[9,1,0],[0,1,9]])
c= np.array([3,1,0])
np.linalg.solve(v,c)

array([ 0.02777778,  0.75      , -0.08333333])

## EIGEN VALUES

In [26]:
e= np.array([[2,0,9],[2,1,7],[2,5,5]])

In [31]:
w,v =np.linalg.eig(e)
v

array([[-0.59047276, -0.96093   , -0.81216284],
       [-0.52942933,  0.11356943, -0.37847767],
       [-0.60913587,  0.25241933,  0.44401146]])

In [34]:
# FIRST EIGEN vector
v1= v[:,0]
print(v1)

[-0.59047276 -0.52942933 -0.60913587]


## vector product

In [ ]:
# cross product

In [14]:
b1= np.array([3,5,6])

In [15]:
b2=np.array([4,7,1])

In [17]:
print(np.cross(b1,b2))

[-37  21   1]


In [ ]:
# dot product

In [18]:
print(np.dot(b1,b2))

53
