In [1]:
import numpy as np

In [4]:
# ZERO MATRICS
a=np.zeros((2,4), dtype='int32')
print(a)

[[0 0 0 0]
 [0 0 0 0]]


In [5]:
# Ones MATRICS
a=np.ones((2,4), dtype='int32')
print(a)

[[1 1 1 1]
 [1 1 1 1]]


In [7]:
# Default matrics
a= np.full((3,4),66)
print(a)

[[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]


In [8]:
# RANDOM MATRICS
b= np.random.rand(2,5)
print(b)

[[0.74441871 0.6922326  0.6814864  0.13279413 0.19639992]
 [0.24402824 0.35743794 0.16422666 0.51041078 0.57669871]]


In [14]:
c= np.random.randint(1,4,size=(3,3))
print(c)

[[3 1 1]
 [1 3 2]
 [2 3 3]]


In [17]:
# THE IDENTITY MATRIX
d= np.identity(5,dtype='int32')
print(d)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [33]:
# TO REPEATE A MATRICS
e= np.array([[1,2,3]])
r=np.repeat(e,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
