In [1]:
import numpy as np

In [3]:
a=np.array([2,3,5,7,9,10,11,12])

In [4]:
print(a[1:-1])
print(a[3:6])

[ 3  5  7  9 10 11]
[ 7  9 10]


In [2]:
b=np.array([[2,3,4],[5,7,1],[0,6,9]])
print(b)

[[2 3 4]
 [5 7 1]
 [0 6 9]]


In [11]:
print(b[1:,:-1])
print(b[:-1,:1])

[[5 7]
 [0 6]]
[[2]
 [5]]


## VECTORICE AND LAMBDA

In [5]:
a=np.array(['jim','josh','ravi','nandu','suyash','kumkum','jimmy','jack'])

In [25]:
# lamda returns the value of element 
f=(lambda s: s[2])(a)
print(f)

ravi


In [28]:
# vectorice return a array with first letter
g=np.vectorize(lambda s: s[0])(a)
print(g)

['j' 'j' 'r' 'n' 's' 'k' 'j' 'j']


In [55]:
# USE TO FIND NAMES STARTING WITH SPECIFIC WORD
name_j=np.vectorize(lambda s: s[0])(a)=='j'
print(name_j)
print(a[name_j])
c=0
for i in range(len(name_j)):
    if name_j[i]==True:
        c+=1
print(c)

[ True  True False False False False  True  True]
['jim' 'josh' 'jimmy' 'jack']
4
